name: CI

on:
  pull_request:
  push:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install -r codex-env/requirements.txt
          pip install -e .
      - name: Tests
        run: |
          PYTHONPATH=src pytest -q -m "not slow" --cov=src/hei_nw --cov-report=term --cov-report=xml
      - name: Diff coverage
        run: |
          git fetch origin main --depth=1 || true
          diff-cover coverage.xml --compare-branch=origin/main --fail-under=85
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
      - name: Parity guard (B1 empty ≈ B0)
        env:
          MODEL: sshleifer/tiny-gpt2
          PYTHONPATH: src
        run: bash scripts/run_parity_guard.sh
      - name: M2 smoke (tiny model)
        env:
          MODEL: sshleifer/tiny-gpt2
          PYTHONPATH: src
        run: bash scripts/run_m2_retrieval_ci.sh
      - name: Gate non-empty predictions
        run: bash scripts/gate_non_empty_predictions.sh reports/m2-retrieval-stack/A_B1_metrics.json
      - name: QA prompting + metrics smoke
        env:
          MODEL: sshleifer/tiny-gpt2
          MAX_OUTPUT_TOKENS: "32"
        run: bash scripts/ci_qa_prompting_smoke.sh
      - name: No stubs
        run: |
          if git grep -nE "(TODO|FIXME|pass  # stub|raise NotImplementedError)" -- ':!tests' ':!prompts' ':!planning' ':!reviews' ':!.github/workflows/ci.yml' ':!scripts/grep_no_stubs.sh'; then
            echo "Stubs found."
            exit 1
          else
            echo "No stubs."
          fi
