name: CI

on:
  pull_request:
  push:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r codex-env/requirements.txt
          pip install -e .
      - name: Format
        run: black --check .
      - name: Lint
        run: ruff .
      - name: Type check
        run: mypy .
      - name: Tests
        run: |
          PYTHONPATH=src pytest -q -m "not slow" --cov=src/hei_nw --cov-report=term --cov-report=xml
      - name: Diff coverage
        run: |
          git fetch origin main --depth=1 || true
          diff-cover coverage.xml --compare-branch=origin/main --fail-under=85
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
      - name: No stubs
        run: bash scripts/grep_no_stubs.sh
